server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  neo4j:
    uri: ${SPRING_NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${SPRING_NEO4J_AUTHENTICATION_USERNAME:neo4j}
      password: ${SPRING_NEO4J_AUTHENTICATION_PASSWORD:test}
  data:
    neo4j:
      database: ${SPRING_DATA_NEO4J_DATABASE:social}

springdoc:
  api-docs:
    enabled: true
    path: ${SPRINGDOC_API_DOCS_PATH:/v3/api-docs}
  swagger-ui:
    enabled: true
    path: ${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui/index.html}

app:
  seed: ${APP_SEED:false}
