version: "3.9"

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "${NEO4J_HTTP_PORT}:7474"
      - "${NEO4J_BOLT_PORT}:7687"
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASS}"
      NEO4J_dbms_default__database: "${NEO4J_DB}"
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u ${NEO4J_USER} -p ${NEO4J_PASS} 'RETURN 1;' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redsocial-app
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      SERVER_PORT: "${APP_PORT}"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
      SPRING_NEO4J_URI: "${NEO4J_BOLT}"
      SPRING_NEO4J_AUTHENTICATION_USERNAME: "${NEO4J_USER}"
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: "${NEO4J_PASS}"
      SPRING_DATA_NEO4J_DATABASE: "${NEO4J_DB}"
      APP_SEED: "${SEED}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
